@baseUrl = http://localhost:3000

### Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
        "title": "Furioza",
        "duration": 69,
        "budget": 200000,
        "link": "https://www.imdb.com/title/tt0086250/"

}

